services:
  chartdb:
    image: ghcr.io/chartdb/chartdb:latest
    container_name: chartdb
    restart: unless-stopped
    ports:
     - "9501:80"
    deploy:
      resources:
        limits:
          memory: 500M
