services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      sonarqube_db:
        condition: service_healthy
    ports:
      - "9500:9000"
    volumes:
      - ${HOME:-${USERPROFILE}}/.sonarqube/data:/opt/sonarqube/data
      - ${HOME:-${USERPROFILE}}/.sonarqube/extensions:/opt/sonarqube/extensions
      - ${HOME:-${USERPROFILE}}/.sonarqube/logs:/opt/sonarqube/logs
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar  # Explicitly set the JDBC URL for PostgreSQL
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    networks:
      - sonarqube_network
    deploy:
      resources:
        limits:
          memory: 3G

  sonarqube_db:
    image: postgres:16
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "43448:5432"
    volumes:
      - ${HOME:-${USERPROFILE}}/.sonarqube/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - sonarqube_network
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  sonarqube_network:
    driver: bridge
